# coding: utf-8

# flake8: noqa
"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from event_stats_client.models.base_response_schema import BaseResponseSchema
from event_stats_client.models.change_seat import ChangeSeat
from event_stats_client.models.current_price import CurrentPrice
from event_stats_client.models.event_source import EventSource
from event_stats_client.models.event_store_stats_request_schema import EventStoreStatsRequestSchema
from event_stats_client.models.http_validation_error import HTTPValidationError
from event_stats_client.models.previous_price import PreviousPrice
from event_stats_client.models.seat_price import SeatPrice
from event_stats_client.models.validation_error import ValidationError
from event_stats_client.models.validation_error_loc_inner import ValidationErrorLocInner
