# coding: utf-8

"""
    FastAPI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict
from typing import Any, ClassVar, Dict, List
from event_stats_client.models.change_seat import ChangeSeat
from event_stats_client.models.seat_price import SeatPrice
from typing import Optional, Set
from typing_extensions import Self

class SeatStats(BaseModel):
    """
    SeatStats
    """ # noqa: E501
    changed_listings: List[ChangeSeat]
    removed_listings: List[SeatPrice]
    new_listings: List[SeatPrice]
    __properties: ClassVar[List[str]] = ["changed_listings", "removed_listings", "new_listings"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SeatStats from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in changed_listings (list)
        _items = []
        if self.changed_listings:
            for _item_changed_listings in self.changed_listings:
                if _item_changed_listings:
                    _items.append(_item_changed_listings.to_dict())
            _dict['changed_listings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in removed_listings (list)
        _items = []
        if self.removed_listings:
            for _item_removed_listings in self.removed_listings:
                if _item_removed_listings:
                    _items.append(_item_removed_listings.to_dict())
            _dict['removed_listings'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in new_listings (list)
        _items = []
        if self.new_listings:
            for _item_new_listings in self.new_listings:
                if _item_new_listings:
                    _items.append(_item_new_listings.to_dict())
            _dict['new_listings'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SeatStats from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "changed_listings": [ChangeSeat.from_dict(_item) for _item in obj["changed_listings"]] if obj.get("changed_listings") is not None else None,
            "removed_listings": [SeatPrice.from_dict(_item) for _item in obj["removed_listings"]] if obj.get("removed_listings") is not None else None,
            "new_listings": [SeatPrice.from_dict(_item) for _item in obj["new_listings"]] if obj.get("new_listings") is not None else None
        })
        return _obj


